name: Generate and Upload Test Coverage Results
on:
  push:
    branches:
      - main
    paths:
      - '**.fs'
      - '.github/workflows/coverage.yml'
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.*
      - name: Test
        run: |
          dotnet test --verbosity normal --results-directory coverage --collect:"XPlat Code Coverage" --settings coverlet.runsettings
          mv coverage/*/coverage.info coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
